version: '3.8'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: PUBLIC
#    networks:
#      - mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080
  myapp:
    image: myapp:1.0
    ports:
      - 5001:5000