//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 11:56:05 AM MSK 
//


package com.soskin.store.springstore.soap;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SoapProduct" type="{http://www.soskin.com/store/springstore/SoapProducts}SoapProduct"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "soapProduct"
})
@XmlRootElement(name = "GetSoapProductByIdResponse")
public class GetSoapProductByIdResponse {

    @XmlElement(name = "SoapProduct", required = true)
    protected SoapProduct soapProduct;

    /**
     * Gets the value of the soapProduct property.
     * 
     * @return
     *     possible object is
     *     {@link SoapProduct }
     *     
     */
    public SoapProduct getSoapProduct() {
        return soapProduct;
    }

    /**
     * Sets the value of the soapProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoapProduct }
     *     
     */
    public void setSoapProduct(SoapProduct value) {
        this.soapProduct = value;
    }

}
