//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 11:56:05 AM MSK 
//


package com.soskin.store.springstore.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soskin.store.springstore.soapproducts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soskin.store.springstore.soapproducts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSoapProductByIdRequest }
     * 
     */
    public GetSoapProductByIdRequest createGetSoapProductByIdRequest() {
        return new GetSoapProductByIdRequest();
    }

    /**
     * Create an instance of {@link GetAllSoapProductsRequest }
     * 
     */
    public GetAllSoapProductsRequest createGetAllSoapProductsRequest() {
        return new GetAllSoapProductsRequest();
    }

    /**
     * Create an instance of {@link GetSoapProductByIdResponse }
     * 
     */
    public GetSoapProductByIdResponse createGetSoapProductByIdResponse() {
        return new GetSoapProductByIdResponse();
    }

    /**
     * Create an instance of {@link SoapProduct }
     * 
     */
    public SoapProduct createSoapProduct() {
        return new SoapProduct();
    }

    /**
     * Create an instance of {@link GetAllSoapProductsResponse }
     * 
     */
    public GetAllSoapProductsResponse createGetAllSoapProductsResponse() {
        return new GetAllSoapProductsResponse();
    }

}
