server:
  port: 8189
  servlet:
    context-path: /web-market-core
utils:
  cart:
    prefix: SPRING_WEB_

#  //тут поменяны драйверы и урл с указанием деф названием  схемы Public для флайвей //Todo
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/PUBLIC

    username: root
    password: admin
  jpa:
    hibernate:
      #      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update

    show-sql: true
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: sa
#    password:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
integrations:
  cart-service:
    url: http://localhost:5555/cart
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000
